package Chevauchee_fantastique_DIAZ;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;


public class Fenetre_jeu extends javax.swing.JFrame {
    boolean [][]allume;
}
    
    public Fenetre_jeu(){
        initComponents();
        allume = new boolean[6][6];
        for (int i = 0; i < 6; i++) {
        for (int j = 0; j < 6; j++) {
        allume[i][j] = true;
    }
        
    }
        
        
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(6, 6));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        jButton2.setText("jButton2");
        getContentPane().add(jButton2);

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setText("jButton2");
        getContentPane().add(jButton3);

        jButton4.setText("jButton2");
        getContentPane().add(jButton4);

        jButton5.setBackground(new java.awt.Color(255, 255, 51));
        jButton5.setText("jButton2");
        getContentPane().add(jButton5);

        jButton6.setText("jButton2");
        getContentPane().add(jButton6);

        jButton7.setText("jButton2");
        getContentPane().add(jButton7);

        jButton8.setBackground(new java.awt.Color(255, 255, 51));
        jButton8.setText("jButton2");
        getContentPane().add(jButton8);

        jButton9.setText("jButton2");
        getContentPane().add(jButton9);

        jButton10.setBackground(new java.awt.Color(255, 255, 51));
        jButton10.setText("jButton2");
        getContentPane().add(jButton10);

        jButton11.setText("jButton2");
        getContentPane().add(jButton11);

        jButton12.setBackground(new java.awt.Color(255, 255, 51));
        jButton12.setText("jButton2");
        getContentPane().add(jButton12);

        jButton13.setBackground(new java.awt.Color(255, 255, 51));
        jButton13.setText("jButton2");
        getContentPane().add(jButton13);

        jButton14.setText("jButton2");
        getContentPane().add(jButton14);

        jButton15.setBackground(new java.awt.Color(255, 255, 51));
        jButton15.setText("jButton2");
        getContentPane().add(jButton15);

        jButton16.setText("jButton2");
        getContentPane().add(jButton16);

        jButton17.setBackground(new java.awt.Color(255, 255, 51));
        jButton17.setText("jButton2");
        getContentPane().add(jButton17);

        jButton18.setText("jButton2");
        getContentPane().add(jButton18);

        jButton19.setText("jButton2");
        getContentPane().add(jButton19);

        jButton20.setBackground(new java.awt.Color(255, 255, 51));
        jButton20.setText("jButton2");
        getContentPane().add(jButton20);

        jButton21.setText("jButton2");
        getContentPane().add(jButton21);

        jButton22.setBackground(new java.awt.Color(255, 255, 51));
        jButton22.setText("jButton2");
        getContentPane().add(jButton22);

        jButton23.setText("jButton2");
        getContentPane().add(jButton23);

        jButton24.setBackground(new java.awt.Color(255, 255, 51));
        jButton24.setText("jButton2");
        getContentPane().add(jButton24);

        jButton25.setBackground(new java.awt.Color(255, 255, 51));
        jButton25.setText("jButton2");
        getContentPane().add(jButton25);

        jButton26.setText("jButton2");
        getContentPane().add(jButton26);

        jButton27.setBackground(new java.awt.Color(255, 255, 51));
        jButton27.setText("jButton2");
        getContentPane().add(jButton27);

        jButton28.setText("jButton2");
        getContentPane().add(jButton28);

        jButton29.setBackground(new java.awt.Color(255, 255, 51));
        jButton29.setText("jButton2");
        getContentPane().add(jButton29);

        jButton30.setText("jButton2");
        getContentPane().add(jButton30);

        jButton31.setText("jButton2");
        getContentPane().add(jButton31);

        jButton32.setBackground(new java.awt.Color(255, 255, 51));
        jButton32.setText("jButton2");
        getContentPane().add(jButton32);

        jButton33.setText("jButton2");
        getContentPane().add(jButton33);

        jButton34.setBackground(new java.awt.Color(255, 255, 51));
        jButton34.setText("jButton2");
        getContentPane().add(jButton34);

        jButton35.setText("jButton2");
        getContentPane().add(jButton35);

        jButton36.setBackground(new java.awt.Color(255, 255, 51));
        jButton36.setText("jButton2");
        getContentPane().add(jButton36);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jButton1.setBackground(Color.GRAY);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables

