/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */

public class FenetreQuiz extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    Question[] questions; 
    int index = 0;
    int score = 0;
    
    public FenetreQuiz() {
        initComponents();
        
        questions = new Question[5];
        
        questions[0]= new Question("Combien y'a t'il d'écuries en F1 ?", "10", "8", "12", "20", 1);
        questions[1]= new Question("Combien de titres Lewis Hamilton détient il ? ", "5", "7", "6", "8", 2);
        questions[2]= new Question("Qui a gagné le championnat en 2016 ?", "Hamilton", "Vettel", "Rosberg", "Raikkonen", 3);
        questions[3]= new Question("Quel est le circuit le plus rapide ?", "Monza", "Baku", "Monaco", "Silverstone",1);
        questions[4]= new Question("Quel type de moteur est utilisé en Formule 1 moderne ?", "V8", "V6", "V10", "V12",2);
        
        afficherQuestion();
    }   
    
        private void Repondre(int choix){
            Question q = questions[index];
            if (choix== q.getIndexBonneReponse()){
                lblFeedback.setText("Bonne réponse !");
                score++;
                
            } else {
                lblFeedback.setText("Mauvaise réponse ! Dommage ");
            }
            
        lblScore.setText("Score : "+ score);   
        
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        }
        
        private void afficherQuestion() {
            Question q = questions[index];
            lblQuestion.setText(q.getIntitule());
            btnRep1.setText(q.getProposition1());
            btnRep2.setText(q.getProposition2());
            btnRep3.setText(q.getProposition3());
            btnRep4.setText(q.getProposition4());
            
            lblFeedback.setText("");
            
            btnRep1.setEnabled(true);
            btnRep2.setEnabled(true);
            btnRep3.setEnabled(true);
            btnRep4.setEnabled(true);
           
            
        }
                
        


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnSuivante = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuestion.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        lblQuestion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQuestion.setText("question");
        getContentPane().add(lblQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        btnRep1.setBackground(new java.awt.Color(255, 153, 204));
        btnRep1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRep1.setText("rep1");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 110, -1));

        btnRep2.setBackground(new java.awt.Color(255, 153, 204));
        btnRep2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRep2.setText("rep2");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 98, 120, -1));

        btnRep3.setBackground(new java.awt.Color(255, 153, 204));
        btnRep3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRep3.setText("rep3");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 150, 110, -1));

        btnRep4.setBackground(new java.awt.Color(255, 153, 204));
        btnRep4.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        btnRep4.setText("rep4");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 150, 120, -1));

        lblFeedback.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(255, 0, 204));
        lblFeedback.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFeedback.setText("feedback");
        getContentPane().add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 206, -1, 44));

        btnSuivante.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSuivante.setText("suivant");
        btnSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuivanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSuivante, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, -1, -1));

        lblScore.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblScore.setForeground(new java.awt.Color(255, 0, 204));
        lblScore.setText("score");
        lblScore.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(lblScore, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 25, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuivanteActionPerformed
        index++;

        if (index >= questions.length) {
            lblQuestion.setText("Fin du quiz ! Merci d'avoir joué !");
            lblFeedback.setText("Score final : " + score + " /5");
            btnSuivante.setEnabled(false);
        }

        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

        afficherQuestion();
    }//GEN-LAST:event_btnSuivanteActionPerformed

    
    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
        Repondre(2);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
        Repondre(3);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        Repondre(1);
    }//GEN-LAST:event_btnRep4ActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed
        Repondre(1);
    }//GEN-LAST:event_btnRep1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JButton btnSuivante;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

}